### ISSUE TITLE
[User Submitted] HighGear not able to connect to POP3 on mail.eclkc.info

### ISSUE THREAD

**Issue by samu711** [OHS-Hosting-Infrastructure/infrastructure#109]
## Reported By
Sam Nevares (samuel.nevares@hendall.com)
Edgar Gomez (egomez@jbsinternational.com)

## Application Context
HighGear

## Environment Context
Production

## Describe the issue
HighGear is not able to connect to mail.eclkc.info on port 995 using SSL (contact.headstart@eclkc.info) the connection times out.

An error was encountered while connecting to the email server defined in incoming email rule #1.
Source: Rebex.Net.Pop3
Message: Could not connect to the email server for Incoming Email Rule #1.
Instance Id: HighGear_HSICC
 
Stack Trace:
```
Root Exception: 
-----------------------------
   Exception Type: 
   -------------------
   Rebex.Net.Pop3Exception
 
   Error Message: 
   -------------------
   Timeout exceeded.
 
   Error Details: 
   -------------------
   at Rebex.Net.Pop3.QztfFZ()
   at wWGvS.AqmpRGZ.BMJzdYZ(Byte[] , Int32 , Int32 )
   at wWGvS.AqmpRGZ.bHacLVZ(Int32& )
   at Rebex.Net.Pop3.AaSTiH()
   at Rebex.Net.Pop3.cTQZqT(Boolean , Boolean , String& )
   at Rebex.Net.Pop3.Connect(String serverName, Int32 serverPort, TlsParameters parameters, Pop3Security security)
   at HighGearLogic.EmailRules.Pop3Adapter.Connect(String emailServer, Int32 emailServerPort, TlsParameters parameters, Pop3Security security)
   at HighGearLogic.EmailRules.Pop3Adapter.Connect(String emailServer, Int32 emailServerPort, TlsParameters tlsParameters, MailProtocolSecurity security)
   at HighGearLogic.EmailRules.EmailMessagesManager.ConnectAndLoginToEmailServer(String emailServer, String emailUsername, String emailPassword, Int32 emailServerPort, Boolean emailServerEnableSSL, IMailProtocolAdapter server, String folderName)
   at HighGearLogic.EmailRules.EmailMessagesManager.Connect()
   at HighGearLogic.EmailRules.EmailMessagesManager.<GetMailMessages>d__6.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at HighGearLogic.EmailRules.EmailAccountProcessor.ProcessMessages(IEmailAccountProcessorErrorHandler errorHandling, IEmailConnectionInfo connectionInfo)
``` 
 
Instance Id: HighGear_HSICC
 
.NET Framework Version 4.0.30319.42000

## Impact
Contact Center is not receiving emails from contact.headstart@eclkc.info (which is not a huge issue because it's an address where we forward to and gets bounces and error messages)

### Reproducibility
Always. In HighGear using the Test Settings option returns the same message every time.

### Steps to reproduce the behavior:
1. Go to HighGear
2. Click on Administration and then Incoming Email Rules
3. Edit Incoming Email Rule 1 and click on Test Settings.

## Expected Behavior
The email client connects to the POP3 server and downloads the emails.

## Screenshots
![Screen Shot 2021-07-12 at 2 50 23 PM](https://user-images.githubusercontent.com/17690417/125342658-2770da80-e323-11eb-8b81-9ab090229cc4.png)

## Additional Context
It looks like a telnet to the server on that port is working but the servers seems to not recognize the user (contact.headstart@eclkc.info)

**Comment by samu711** [comment]
HighGear is just the client we're using but the problem is reproducible using any client. The problem is that the SSL certificate for mail.eclkc.info has expired. If you run:
`openssl s_client -showcerts -connect mail.eclkc.info:995`
You'll get this section on the response:
`verify error:num=10:certificate has expired
notAfter=May 23 15:46:02 2021 GMT
verify return:1
depth=0 OU = Domain Control Validated, CN = *.eclkc.info
notAfter=May 23 15:46:02 2021 GMT
verify return:1`

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
