### ISSUE TITLE
ECLKC login/PIV login outage investigation

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#155]
There was a brief unknown outage of these services around 2021-07-28 03:08:42 UTC+0 and 2021-07-28 03:37:27 UTC+0

Investigating

**Comment by eeeady** [comment]
secure.eclkc.ohs.acf.hhs.gov points at our loadbalancer named "secure-eclkc-ohs-acf-hhs-gov"

Looking at the loadbalancer data from the lat 24 hours It looks like there was a spike of traffic around 07/27 9pm UTC but i doubt it's correlated. There were a decent number of resets throughout the night as well... but based on historical data that's normal.

**Comment by eeeady** [comment]
All traffic through this loadbalancer is directed at Varnish1.

There was a large amount of cpu load on the machine from 07/27 3am UTC until 07/28 5:40am UTC correlated with additional network traffic.

![Screen Shot 2021-07-28 at 9 14 44 AM](https://user-images.githubusercontent.com/1760850/127358926-6681463a-ae7f-4809-988c-19cee98c20b5.png)


All metrics gathered in cloudwatch between 3-4UTC point at the service stopping/resetting and recovering.

![Screen Shot 2021-07-28 at 9 16 15 AM](https://user-images.githubusercontent.com/1760850/127358906-b8041a01-ab28-4a53-b1cb-c922fd446f5c.png)

**Comment by eeeady** [comment]
Checking the nginx logs on the varnish server.... 

there starts a HUGE series of PHP failures at 07/27 23:04:22 EST (close to the 03:08 UTC) and timeouts... all of these are to the local php server.

Some are related to sql query timeouts or disk space issues.

Oddly nothing stands out in the php-fpm logs.

**Comment by eeeady** [comment]
Checking tomcat1 metrics... i see an outbound network spike at around 3am UTC 
![Screen Shot 2021-07-28 at 9 30 11 AM](https://user-images.githubusercontent.com/1760850/127360960-25a9c104-fe34-4cf4-b169-cc75b90ce554.png)

**Comment by eeeady** [comment]
Nothing interesting on Tomcat1. Gonna go look at Mariadb now.

**Comment by eeeady** [comment]
looking at mariadb we have a couple of sql database checks/repairs/optimization running at 11:15pm on top of backups at ~11:30pm.

We tried the optimization job that ran at around that time and it did not contribute to load or filling up disk space.

Might be a coincidence that the disk space fills up around the same time on mariadb... should still fix that.

**Comment by eeeady** [comment]
Nothing of interest in the mariadb logs (in the database) checking the error.log... which I don't think gets rotated (ADD A FIXME)

I don't know if this is related but certainly this machine needs some love.

**Comment by kilbergr** [comment]
From Tomcat1, /var/log/user-mgmt/error.log

```
7/27/2021, 11:09:20 PM
Message :: Lock wait timeout exceeded; try restarting transaction
Stack :: SequelizeDatabaseError: Lock wait timeout exceeded; try restarting transaction
    at Query.formatError (/opt/user-mgmt/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/opt/user-mgmt/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
...
7/27/2021, 11:36:18 PM
Message :: Operation timeout
Stack :: SequelizeConnectionAcquireTimeoutError: Operation timeout
    at ConnectionManager.getConnection (/opt/user-mgmt/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:288:48)
```

**Comment by kilbergr** [comment]
In `/opt/tomcat9/logs`, found  cas-2021-07-27-23-1.log--looks like CAS was still working fine at 11:07pm-11:09pm and later 7/27.

**Comment by kilbergr** [comment]
n Tomcat1 , /opt/tomcat9/logs, found cas-2021-07-27-23-1.log--at 11:18, there's a stack trace.

```
ACTION: DELEGATED_CLIENT_SUCCESS
   2058 APPLICATION: CAS
   2059 WHEN: Tue Jul 27 23:18:45 EDT 2021
   2062 =============================================================
   2063
   2064 >
   2068 =============================================================
   2071 ACTION: AUTHENTICATION_EVENT_TRIGGERED
   2077
   2078 >
   2079 2021-07-27 23:19:00,533 WARN [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] - <SQL Error: 1205, S        QLState: HY000>
   2080 2021-07-27 23:19:00,533 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] - <(conn=1505791) Lo        ck wait timeout exceeded; try restarting transaction>
   2081 2021-07-27 23:19:00,537 ERROR [org.apereo.cas.web.flow.login.CreateTicketGrantingTicketAction] - <cou        ld not execute statement; SQL [n/a]; nested exception is org.hibernate.PessimisticLockException: coul        d not execute statement>
   2082 org.springframework.dao.PessimisticLockingFailureException: could not execute statement; SQL [n/a]; n        ested exception is org.hibernate.PessimisticLockException: could not execute statement
   2083         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(Hib        ernateJpaDialect.java:292) ~[spring-orm-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2084         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(Hibern        ateJpaDialect.java:254) ~[spring-orm-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2085         at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:537)         ~[spring-orm-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2086         at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(A        bstractPlatformTransactionManager.java:744) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2087         at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(Abstract        PlatformTransactionManager.java:712) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2088         at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfte        rReturning(TransactionAspectSupport.java:619) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2089         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransacti        on(TransactionAspectSupport.java:372) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2090         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInter        ceptor.java:99) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2091         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvoc        ation.java:186) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2092         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProx        y.java:747) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2093         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInt        erceptor.java:93) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
2094         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvoc        ation.java:186) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2095         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProx        y.java:747) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2096         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibA        opProxy.java:689) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2097         at org.apereo.cas.DefaultCentralAuthenticationService$$EnhancerBySpringCGLIB$$ea68ca53.create        TicketGrantingTicket(<generated>) ~[cas-server-core-6.1.7.1.jar:6.1.7.1]
   2098         at org.apereo.cas.web.flow.login.CreateTicketGrantingTicketAction.createOrUpdateTicketGrantin        gTicket(CreateTicketGrantingTicketAction.java:163) ~[cas-server-support-actions-6.1.7.1.jar:6.1.7.1]
   2099         at org.apereo.cas.web.flow.login.CreateTicketGrantingTicketAction.doExecute(CreateTicketGrant        ingTicketAction.java:108) ~[cas-server-support-actions-6.1.7.1.jar:6.1.7.1]
   2100         at org.springframework.webflow.action.AbstractAction.execute(AbstractAction.java:188) ~[sprin        g-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2101         at jdk.internal.reflect.GeneratedMethodAccessor442.invoke(Unknown Source) ~[?:?]
   2102         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java        :43) ~[?:?]
   2103         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   2104         at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:279) ~[spring-c        ore-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2105         at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(G        enericScope.java:499) ~[spring-cloud-context-2.2.0.RC1.jar:2.2.0.RC1]
   2106         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvoc        ation.java:186) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2107         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~        [spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2108         at com.sun.proxy.$Proxy430.execute(Unknown Source) ~[?:?]
 2109         at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:51) ~[spr        ing-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2110         at org.springframework.webflow.action.EvaluateAction.doExecute(EvaluateAction.java:77) ~[spri        ng-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2111         at org.springframework.webflow.action.AbstractAction.execute(AbstractAction.java:188) ~[sprin        g-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2112         at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:51) ~[spr        ing-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2113         at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:101) ~[spring-webf        low-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2114         at org.springframework.webflow.engine.State.enter(State.java:194) ~[spring-webflow-2.5.1.RELE        ASE.jar:2.5.1.RELEASE]
   2115         at org.springframework.webflow.engine.Transition.execute(Transition.java:228) ~[spring-webflo        w-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2116         at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:3        95) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2117         at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlCo        ntextImpl.java:214) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2118         at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.jav        a:116) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2119         at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547) ~[spring-webflow-2.5.1.        RELEASE.jar:2.5.1.RELEASE]
   2120         at org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.ja        va:390) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2121         at org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestContr        olContextImpl.java:210) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2122         at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105) ~[spring-webf        low-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2123         at org.springframework.webflow.engine.State.enter(State.java:194) ~[spring-webflow-2.5.1.RELE        ASE.jar:2.5.1.RELEASE]
   2124         at org.springframework.webflow.engine.Transition.execute(Transition.java:228) ~[spring-webflo        w-2.5.1.RELEASE.jar:2.5.1.RELEASE]
2125         at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:3        95) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2126         at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlCo        ntextImpl.java:214) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2127         at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.jav        a:116) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2128         at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547) ~[spring-webflow-2.5.1.        RELEASE.jar:2.5.1.RELEASE]
   2129         at org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.ja        va:390) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2130         at org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestContr        olContextImpl.java:210) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2131         at org.springframework.webflow.engine.ViewState.handleEvent(ViewState.java:231) ~[spring-webf        low-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2132         at org.springframework.webflow.engine.ViewState.resume(ViewState.java:195) ~[spring-webflow-2        .5.1.RELEASE.jar:2.5.1.RELEASE]
   2133         at org.springframework.webflow.engine.Flow.resume(Flow.java:537) ~[spring-webflow-2.5.1.RELEA        SE.jar:2.5.1.RELEASE]
   2134         at org.springframework.webflow.engine.impl.FlowExecutionImpl.resume(FlowExecutionImpl.java:25        9) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2135         at org.springframework.webflow.executor.FlowExecutorImpl.resumeExecution(FlowExecutorImpl.jav        a:168) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2136         at jdk.internal.reflect.GeneratedMethodAccessor626.invoke(Unknown Source) ~[?:?]
   2137         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java        :43) ~[?:?]
   2138         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   2139         at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:279) ~[spring-c        ore-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2140         at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(G        enericScope.java:499) ~[spring-cloud-context-2.2.0.RC1.jar:2.2.0.RC1]
2141         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvoc        ation.java:186) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2142         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~        [spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2143         at com.sun.proxy.$Proxy441.resumeExecution(Unknown Source) ~[?:?]
   2144         at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handle(FlowHandlerAdapter.java:        254) ~[spring-webflow-2.5.1.RELEASE.jar:2.5.1.RELEASE]
   2145         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)         ~[spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2146         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[        spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2147         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006        ) ~[spring-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2148         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[sprin        g-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2149         at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[servlet-api.jar:?]
   2150         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spri        ng-webmvc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
   2151         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
   2152         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.ja        va:231) ~[catalina.jar:9.0.33]
   2153         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)         ~[catalina.jar:9.0.33]
   2154         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.        jar:9.0.33]
   2155         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.ja        va:193) ~[catalina.jar:9.0.33]
   2156         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)         ~[catalina.jar:9.0.33]
   2157         at org.apereo.cas.web.support.AuthenticationCredentialsThreadLocalBinderClearingFilter.doFilt        er(AuthenticationCredentialsThreadLocalBinderClearingFilter.java:28) ~[cas-server-core-web-api-6.1.7.        1.jar:6.1.7.1]
   2158         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.ja        va:193) ~[catalina.jar:9.0.33]
...
```

**Comment by eeeady** [comment]
Ah... there's a jenkins job that runs nightly at around 11:12 Last night's failed with a disk space error https://jenkins.eclkc.info/job/DB%20Export%20-%201.%20production/907/console

**Comment by kilbergr** [comment]
MariaDB restarted `Thu 2021-07-22 21:08:51 EDT; 5 days ago`.

**Comment by eeeady** [comment]
Mariadb instance metrics from the time period show a plummet in cpu at around downtime window
![Screen Shot 2021-07-28 at 11 45 40 AM](https://user-images.githubusercontent.com/1760850/127378763-eb881e26-f841-40f3-b4c2-75aae4e3e024.png)

**Comment by kilbergr** [comment]
At this point, it seems like:
DB locked up, did not restart. Something triggered to clear out queries (maybe queries timed out?). DB was unable to accept those connections.

**Comment by kilbergr** [comment]
MariaDB mysql config:
```
 23 ####################
 24 ### Query Cache Opt
 25 #####################
 26 query_cache_size=256M
 27 query_cache_type=1
 28 query_cache_limit=1
 29 max_connections = 400
 30 max_allowed_packet=500M
```

**Comment by eeeady** [comment]
Chunked up the error log file and found this juicy bit

```
2021-07-27 23:07:04 0 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
2021-07-27 23:07:04 0 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_u2021-07-27 23:40:22 1505909 [Note] Detected table cache mutex contention at instance 2: 21% waits. Additional table cache instance activated. Number of instances after activation: 3.
2021-07-27 23:40:22 1505992 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
2021-07-27 23:40:22 1505992 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
```
There's a huge gap between 23:07:04 and 23:40:22... the service was choking at this time.

**Comment by eeeady** [comment]
Reading the binary logs.... (giving me a headache) found:

```
#210727 23:05:45 server id 1  end_log_pos 212041836 CRC32 0x5704da9c    Query   thread_id=1505718       exec_time=0     error_code=0
use `drupalprod`/*!*/;
SET TIMESTAMP=1627441545/*!*/;
SET @@session.sql_mode=367263791/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=45,@@session.collation_connection=45,@@session.collation_server=8/*!*/;
INSERT INTO watchdog (uid, type, message, variables, severity, link, location, referer, hostname, timestamp) VALUES ('0', 'php', '%type: @message in %function (line %line of %file).', 'a:6:{s:5:\"%type\";s:45:\"Drupal\\Core\\Database\\DatabaseExceptionWrapper\";s:8:\"@message\";s:1186:\"SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction: INSERT INTO {cache_data} (cid, expire, created, tags, checksum, data, serialized) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6) ON DUPLICATE KEY UPDATE cid = VALUES(cid), expire = VALUES(expire), created = VALUES(created),...
```

**Comment by eeeady** [comment]
I believe this was a coincidence of multiple events.

We should really add more disk space to the mariadb instance so we can eliminate disk space utilization as a possible issue.
We will be able to get better information and telemetry if we move these databases into RDS
